# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-17 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180117_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
