# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-18 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180117_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='client_owner',
            field=models.ManyToManyField(to='main.Client'),
        ),
    ]
