# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-18 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_client_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='client_owner',
        ),
        migrations.AddField(
            model_name='cart',
            name='client_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Client'),
            preserve_default=False,
        ),
    ]
